server:
  port: 8080

logging:
  level:
    io:
      mark:
        cache : info

spring:
  redis:
#    host: 192.168.3.13
#    port: 6380
#    timeout: 20000
#    password:
    application:
      name: spring-boot-redis
    sentinel:
      master: mymaster
      nodes: 192.168.3.13:26379,192.168.3.13:26380
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-wait: