server:
  port: 8080

logging:
  level:
    io:
      kimmking:
        cache : info

# 作业，在这里使用spring boot配置各项内容，
spring:
  redis:
    host: 192.168.3.13
    port: 6380
    timeout: 20000
    #    集群环境打开下面注释，单机不需要打开
    #    cluster:
    #      集群信息
    #      nodes: xxx.xxx.xxx.xxx:xxxx,xxx.xxx.xxx.xxx:xxxx,xxx.xxx.xxx.xxx:xxxx
    #      #默认值是5 一般当此值设置过大时，容易报：Too many Cluster redirections
    #      maxRedirects: 3
    password:
    application:
      name: spring-boot-redis
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-wait: